- hosts: all
  become: true
  gather_facts: true

  vars:
    POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
    POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}

  roles:
    - docker
    - network
    - database
    - proxy
    - app
