- hosts: all
  become: true
  gather_facts: true

  vars:
    POSTGRES_USER: "{{ POSTGRES_USER }}"
    POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
    POSTGRES_DB: "{{ POSTGRES_DB }}"
    DOCKER_NETWORK: "{{ DOCKER_NETWORK }}"


  roles:
    - docker
    - network
    - database
    - proxy
    - app
