- name: Run database container
  community.docker.docker_container:
    name: my-database
    image: neilde23/tp-devops-database:latest
    pull : true
    recreate: true
    force_kill: true
    state: started
    env:
      POSTGRES_USER: "{{ POSTGRES_USER }}"
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - name: "{{ DOCKER_NETWORK }}"
