- name: Run simple-api container
  community.docker.docker_container:
    name: simple-api
    image: neilde23/tp-devops-simple-api:latest
    pull : true
    recreate: true
    force_kill: true
    state: started
    ports:
      - 8080:8080
    networks:
      - name: "{{ DOCKER_NETWORK }}"
    env:
      DATABASE_HOST: my-database
      DATABASE_PASSWORD: "{{ POSTGRES_PASSWORD }}"
