- name: Run simple-api container
  community.docker.docker_container:
    name: simple-api
    image: neilde23/tp-devops-simple-api:latest
    state: started
    ports:
      - 8081:8080
    networks:
      - name: "{{ DOCKER_NETWORK }}"
    env:
      DATABASE_HOST: my-database
      DATABASE_PASSWORD: "{{ DOCKER_NETWORK }}"
