- name: Run simple-api container
  community.docker.docker_container:
    name: front
    image: neilde23/tp-devops-front:latest
    pull: true
    recreate: true
    force_kill: true
    state: started
    restart_policy: always
    networks:
      - name: "{{ DOCKER_NETWORK }}"