- name: Run simple-api container
  community.docker.docker_container:
    name: front
    image: neilde23/tp-devops-front:latest
    state: started
    restart_policy: always
    published_ports:
      - "3000:3000"
    networks:
      - name: "{{ DOCKER_NETWORK }}"