name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["SonarCloud Analysis"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    environment: dockerhub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Build Vue front
        working-directory: Github_Actions/TP/front
        run: |
          yarn config set strict-ssl false
          yarn install
          yarn build

      - name: Move Vue dist to http-server
        run: |
          rm -rf http-server/dist
          cp -r front/dist http-server/
    
      - name: Login to DockerHub
        run: echo "${{ secrets.PASSWORD }}" | docker login --username ${{ secrets.MAIL }} --password-stdin

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: Github_Actions/TP/simple-api
          tags:  ${{ secrets.USERNAME }}/tp-devops-simple-api:latest
          push: true

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: Github_Actions/TP/database
          tags:  ${{ secrets.USERNAME }}/tp-devops-database:latest
          push: true

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: Github_Actions/TP/http-server
          tags:  ${{ secrets.USERNAME }}/tp-devops-http-server:latest
          push: true
