name: CI devops 2025

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: mvn clean verify --file Github_Actions/TP/simple-api/pom.xml

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: Github_Actions/TP/simple-api
          push: true
          tags: neilde23/simpleapi:latest

      - name: Build and push database
        uses: docker/build-push-action@v6
        with:
          context: Github_Actions/TP/database
          push: true
          tags: neilde23/my-database:latest

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: Github_Actions/TP/http-server
          push: true
          tags: neilde23/my-proxy:latest

      # - name: Login to DockerHub
      #   run: echo "${{ secrets.PASSWORD }}" | docker login --username ${{ secrets.MAIL }} --password-stdin


